### ISSUE TITLE
More docs

### ISSUE THREAD

**Issue by Remonell** [halloverden/symfony-doctrine-sql-logger-bundle#2]
Hi, I want to test your bundle. Could you please add to your docs where exactly I can find the configuration file and where the log file will get created?

**Comment by tomme87** [comment]
The configuration file should be added to `config/pakcages`. example in the [README](https://github.com/halloverden/symfony-doctrine-sql-logger-bundle#configuration).

This package uses monolog, so where the log get created depends on your monolog config. see https://symfony.com/doc/current/logging.html
