### ISSUE TITLE
Undefined Type 

### ISSUE THREAD

**Issue by Remonell** [halloverden/symfony-doctrine-sql-logger-bundle#5]
Step 1 and Step 2 are working now. Had a look in the vendor folder and noticed those problems:
![Screenshot_4](https://user-images.githubusercontent.com/8575168/114693145-97b69280-9d19-11eb-8158-c64db01cda62.png)

**Comment by erichjsonfosse** [comment]
@Remonell The AddDoctrineLoggersCompilerPass implements the CompilerPassInterface. Are you using the bundle within a Symfony project?

**Comment by tomme87** [comment]
These are not valid problems. since AddDoctrineLoggersCompilerPass implements CompilerPassInterface and AddDoctrineLoggersCompilerPass does exist.

**Comment by erichjsonfosse** [comment]
Closing. @Remonell Reopen if you need to :)
